### ISSUE TITLE
FusionPILOT - prep SharePoint lists

### ISSUE THREAD

**Issue by maxder** [maxder/mdd#24]
- [ ] Add default FusionSearch view to all Products lists
- [ ] Document settings in OneNote

**Comment by Mr-Disco** [comment]
Tracking document. Each list is taking 30 to 60 minutes
http://data.providence.org/sites/hi/HIOM/Documents/myHIway/FusionSearch%20Updates.xlsx

**Comment by maxder** [comment]
This issue was moved to maxder/platform#14
