### ISSUE TITLE
Customer Facing Documentation

### ISSUE THREAD

**Issue by Mr-Disco** [maxder/mdd#7]
#### Data Catalog Modeling Standards
- [x] Develop
- [ ] Convert to PDF
- [ ] Post to DPO
#### Data Catalog Metadata Standards
- [x] Develop
- [ ] Convert to PDF
- [ ] Post to DPO
#### Data Catalog Customer Fulfillment Checklist
- [x] Develop
- [ ] Convert to PDF
- [ ] Post to DPO
#### Data Catalog Customer Fulfillment Process
- [x] Develop
- [ ] Convert to PDF
- [ ] Post to DPO

**Comment by Mr-Disco** [comment]
test

**Comment by Mr-Disco** [comment]
fromal documentation complete. working intake list to match checklist.

**Comment by maxder** [comment]
This issue was moved to maxder/content#3
